### ISSUE TITLE
Default options change how dust renders in other contexts

### ISSUE THREAD

**Issue by jrrbru** [Cellarise/gulp-dust-compile-render#3]
First, thanks for writing this package.

I'm using this as part of a larger project. Some of my .dust files need to be compiled and rendered during my build process - (which is why I'm using this). Others are compiled as part of a Webpack build process to be rendered in the browser.

The problem is that line 73 of lib/index.js blows away Dust's native `format` method. This impacts not just this plugin's compiling, but also the compiling being done during my Webpack build because it's sharing an instance of `dustjs-linkedin` with the main project.

Would it be possible to save the original `format` method and restore it when the compilation for this plugin is done?

**Comment by jrrbru** [comment]
I've created a pull request that seems to fix the problem for me, at least: https://github.com/Cellarise/gulp-dust-compile-render/pull/4

**Comment by JohnMBarry** [comment]
Thanks for the update Jason. Closing issue.
